source ~/.vim/vundle-plugins.vim

syntax on
set number relativenumber
set mouse=a
set shiftwidth=4
set tabstop=4
set whichwrap+=<,>,[,]
set cursorline
set backspace=indent,eol,start
set splitright
set splitbelow
colorscheme onehalfdark

" requires `powerline-fonts` package
let g:airline_powerline_fonts = 1

nnoremap <leader>n :NERDTreeFocus<CR>
nnoremap <C-t> :NERDTreeToggle<CR>
nnoremap <C-f> :NERDTreeFind<CR>
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * NERDTree | if argc() > 0 || exists("s:std_in") | wincmd p | endif
autocmd BufEnter * if tabpagenr('$') == 1 && winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree() | quit | endif
